version: 2

models:
  - name: stg_model_1
    description: test
    columns:
      - name: id 
        description: hocus pocus
        tests:
          - unique
  - name: stg_model_2
    columns:
      - name: id 
        tests:
          - unique
          - not_null