
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'metaplane-dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    linkedin_pages:
      +schema: linkedin_pages # leave blank for just the target_schema
    linkedin_pages_source:
      +schema: linkedin_pages_source # leave blank for just the target_schema
    stripe:
      +schema: stripe # leave blank for just the target_schema
    stripe_source:
      +schema: stripe_source # leave blank for just the target_schema
    hubspot:
      +schema: hubspot # leave blank for just the target_schema
    hubspot_source:
      +schema: hubspot_source # leave blank for just the target_schema
        

vars:
  hubspot_source:
    hubspot_database: raw
    hubspot_schema: hubspot
  stripe_source:
    stripe_database: raw
    stripe_schema: stripe
  linkedin_pages_source:
    linkedin_pages_schema: raw
    linkedin_pages_database: linkedin_company_pages  
